### ISSUE TITLE
Would it be possible for you to provide a template for your thesis?

### ISSUE THREAD

**Issue by linhduongtuan** [Dherse/masterproef#1]
I greatly admire the format of your thesis; however, I find it challenging to reproduce. Would it be possible for you to provide a template for your thesis? This would be a great help to me and to others who are interested in using your format. Your assistance in this matter would be greatly appreciated. Thank you in advance.
Linh

**Comment by Dherse** [comment]
Hello, it's quite late but it's now available at https://github.com/Dherse/ugent-templates.
